name: quant-tsa
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.7
  - numpy==1.18.1
  - pandas==1.1.0
  - alphalens==0.3.6
  - scikit-learn==0.22.1
  - matplotlib==3.2.1
  - seaborn==0.10.1
  - graphviz==2.38
  - python-graphviz
  - yaml==0.1.7
  - pyyaml==5.3.1
  - scipy==1.5.0
  - scikit-learn==0.23.1
  - statsmodels==0.11.0
  - tqdm==4.46.0
  - shap==0.26.0
  - quandl==3.4.2
  - pandas-datareader==0.9.0
  - nltk==3.5.0
  - pip:
    - https://files.pythonhosted.org/packages/34/fe/c3bef165ecca4f33c77c3e97aebf6fcd048c487fb2d1ba964839fa9fc38b/simfin-0.8.1-py3-none-any.whl
    - ratelimit==2.2.0
  
