name: quant-ai4trading
channels:
  - quantopian
  - conda-forge
  - anaconda
dependencies:
  - python==3.5
  - numpy==1.14.2  
  - pandas==0.22.0
  - zipline==1.3.0
  - alphalens==0.3.6
  - scikit-learn==0.22.1
  - matplotlib==3.2.1
  - seaborn==0.8.1
  - graphviz==2.38
  - python-graphviz
  - yaml==0.1.7
  - pyyaml==5.3.1
  - scipy==1.1.0
  - scikit-learn==0.20.0
  - statsmodels==0.9.0
  - tqdm==4.46.0
  - shap==0.26.0
  - quandl==3.4.2
